<%-- filename: customer.jsp | Code Generated by Sidekick is for learning and experimentation purposes only. --%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Customer Results</title>
</head>
<body>

    <h1>Hello, ${customer.fname}!</h1>

    <p>First Name: ${customer.fname}</p>
    <p>Last Name: ${customer.lname}</p>
    <p>Email: ${customer.email}</p>
    <p>Rows inserted: ${rowsCreated}</p>

</body>
</html>
