<%-- filename: login.jsp --%>
<%-- Code Generated by Sidekick is for learning and experimentation purposes only. --%>

<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Customer Login</title>
</head>
<body>

<h1>Customer Login</h1>

<p style="color: red">${error}</p>

<form action="login"
      method="post">

    <label>Email:</label>
    <input type="email" name="email" required>
    <br><br>

    <label>Password:</label>
    <input type="password" name="pass" required>
    <br><br>

    <input type="submit" value="Login">
</form>

</body>
</html>
